deploymentName: accountservice-deployment
serviceName: accountservice
appLabel: accountservice
appName: accountservice

replicaCount: 1

image:
  repository: smartbank/accountservice
  tag: v1

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
rabbitmq_enabled: true
redis_enabled: false