apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice-deployment
  label:
    app: accountservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
        - name: accountservice
          image: smartbank/accountservice:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  selector:
    app: accountservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080