apiVersion: v1
kind: ConfigMap
metadata:
  name: smartbank-configmap
data:
  SPRING_PROFILES_ACTIVE: "prod"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  SPRING_DATA_REDIS_HOST: redis
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
  SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/