apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  label:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.2
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                ConfigMapKeyRef:
                  name: smartbank-configmap
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                ConfigMapKeyRef:
                  name: smartbank-configmap
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - containerPort: 7080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7080
      targetPort: 7080