apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanservice-deployment
  label:
    app: loanservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loanservice
  template:
    metadata:
      labels:
        app: loanservice
    spec:
      containers:
        - name: loanservice
          image: smartbank/loanservice:v1
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: loanservice
spec:
  selector:
    app: loanservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000