server:
  port: 8081
spring:
  application:
    name: customerservice
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3309/customersDB
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
        liveness:
          include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "customerservice"
    description: "smart bank customer application"
    version: "4.0.0"
logging:
  level:
    com:
      smartbank:
        customerservice: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
#resilience4j.circuitbreaker:
#  configs:
#    default:
#      slidingWindowSize: 10
#      failureRateThreshold: 50
#      permittedNumberOfCallsInHalfOpenState: 2
#      waitDurationInOpenState: 10s
axon:
  eventhandling:
    processors:
      customer-group:
        mode: subscribing
  axonserver:
    servers: localhost:8124
