deploymentName: configserver-deployment
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1

image:
  repository: smartbank/configserver
  tag: v1

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

appname_enabled: true
profile_enabled: true
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
rabbitmq_enabled: true
redis_enabled: false