server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///C://Users//gvnsa//IdeaProjects//smartBankConfigs"
        git:
          uri: "https://github.com/Tarun-G-V-N/smart-bank-configs.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
        liveness:
          include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
encrypt:
  key: "viL9dQ9adfRdcdBdaGmo7SDgpBvsxTfXEWN"