deploymentName: messageservice-deployment
serviceName: messageservice
appLabel: messageservice
appName: messageservice

replicaCount: 1

image:
  repository: smartbank/messageservice
  tag: v1

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: true
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
rabbitmq_enabled: true
redis_enabled: false