deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: smartbank/eurekaserver
  tag: v1

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
rabbitmq_enabled: false
redis_enabled: false