server:
  port: 9000
  address: 0.0.0.0
spring:
  application:
    name: "loanservice"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3308/loansDB
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    function:
      definition: updateCommunication
    stream:
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
        liveness:
          include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "loanservice"
    description: "smart bank loans application"
    version: "3.0.0"
logging:
  level:
    com:
      smartbank:
        loanservice: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
axon:
  eventhandling:
    processors:
      loan-group:
        mode: subscribing
  axonserver:
    servers: localhost:8124